### ISSUE TITLE
Sonarqube 7.4 error

### ISSUE THREAD

**Issue by gitphill** [fortify-ps/fortify-integration-sonarqube#3]
We're having difficulty running 2.3 fortify plugin on sonarqube 7.4.
We get the following error message when performing sonarqube scans:

> [ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.6.0.1398:sonar (default-cli) on project lego-ux: Unable to load component class com.fortify.integration.sonarqube.ssc.batch.FortifyIssueMetricsAndSensor: com.fortify.integration.sonarqube.ssc.batch.FortifyIssueMetricsAndSensor has unsatisfied dependency 'class com.fortify.integration.sonarqube.ssc.FortifySSCConnectionFactory' for constructor 'public com.fortify.integration.sonarqube.ssc.batch.FortifyIssueMetricsAndSensor(com.fortify.integration.sonarqube.ssc.FortifySSCConnectionFactory)' from org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer@20bb85b4:80<[Immutable]:org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer@5ec88f9e:9<[Immutable]:org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer@56c0a61e:42<|

Does the plugin support this version of sonarqube?

**Comment by rsenden** [comment]
The new 2.4-alpha release of the plugin should now support any SonarQube version between 6.7 and 7.6 (and probably later versions as well); see https://github.com/fortify-ps/fortify-integration-sonarqube-ssc/releases/tag/v2.4-alpha
