### ISSUE TITLE
Sonar fortify token/user role permissions

### ISSUE THREAD

**Issue by bars0um** [fortify-ps/fortify-integration-sonarqube#5]
It is important to note that the user token utilized by sonar to synchronize with SSC should be assigned a role that has the following privileges/permissions:

1. Upload analysis results
2. View application versions
3. View jobs in queue

**Comment by rsenden** [comment]
Documentation has been updated to list the required permissions: https://github.com/fortify-ps/fortify-integration-sonarqube/commit/c41fad5be599c3e21ec9b4812f02744cdac1b4ae
