### ISSUE TITLE
Sonarqube server error on upload - java.lang.NoClassDefFoundError: org/apache/commons/logging/LogFactory

### ISSUE THREAD

**Issue by bars0um** [fortify-ps/fortify-integration-sonarqube#6]
You may run into the following error upon SSC synchronization with certain versions of SonarQube. 

java.lang.NoClassDefFoundError: org/apache/commons/logging/LogFactory at 

Check to see if the commons-logging library is missing from the sonar/libs/common/ folder, if so adding it may resolve the issue. Potentially it is  best to include the dependency in the fortify-sonar plugin pom...

**Comment by rsenden** [comment]
SonarQube plugins are not allowed to bundle commons-logging, as this library is provided by SonarQube. Apparently they mistakenly removed this library in SonarQube 7.1 (according to some similar bug reports for other plugins), and it was re-added in 7.2.

I have added a note about this in the documentation: https://github.com/fortify-ps/fortify-integration-sonarqube/commit/a45b83a00a56a740748eab018314d4c43770f92d
