### ISSUE TITLE
SonarQube 7.9

### ISSUE THREAD

**Issue by ltischhauser** [fortify-ps/fortify-integration-sonarqube#7]
Recently tried release 2.5 with SonarQube 7.9 and it didn't work.  Do you have a version tested/suggested for that new of SonarQube?

**Comment by rsenden** [comment]
I just tried version 2.6 of the plugin (which has only minor changes compared to 2.5) with SonarQube 7.9.1 Community Edition on Oracle JDK 11.0.5, and the plugin seems to work fine. 

If you are still experiencing this issue, can you please provide some more details, like:

* Which SonarQube edition are you using?
* What Java type & version are you using (Oracle, OpenJDK, ...)?
* What exactly is not working?
* What command line & plugin settings are you using?
* Log files / exception message / ...

**Comment by ltischhauser** [comment]
7.9 (build 26994)
Oracle JDK 11.0.5

Does the plugin require both Fortify and SonarQube to be using https?

**Comment by rsenden** [comment]
The plugin doesn't require either SSC or SonarQube to use https (although for security reasons https is of course recommended).

If you do use https, the relevant (CA) certificates need to be available in the cacerts file of the Java installation used to run the Sonar Scanner.

Again, if you need more assistance with this, please provide more information about what exactly is not working, and share any log output & exception messages.

**Comment by rsenden** [comment]
Issue is being closed as reporter didn't provide any further information.
