### ISSUE TITLE
Importing FPR to Sonarqube does not scan contents of FPR

### ISSUE THREAD

**Issue by lbenhart** [fortify-ps/fortify-integration-sonarqube#8]
Attempting to import an fpr file does not result in the evaluation of said fpr file. 
It appears as if an upload of the fpr is attempted to SSC, only I do not wish to use SCC or FOP.
The scan is completed, and the results are clearly in the fpr file, it appears as if no extraction is even attempted.  Instead, the scanner will scan the directory I am in, not the fpr file I am including.

-bash-4.2$ sonarscanner -Dsonar.projectKey=core_fpr -Dsonar.fortify.reportPath=/path/to/file_fortify.fpr -Dsonar.scm.disabled -Dsonar.fortify.ssc.appversion=2.0 -X
 
14:07:45.775 DEBUG: Work directory: /home/vagrant/tmp/.scannerwork
14:07:45.778 DEBUG: Execution execute
14:07:46.925 DEBUG: Community 7.9.1.27448
14:07:47.662 INFO: Load plugins index
14:07:47.736 DEBUG: GET 200 http://localhost:9000/api/plugins/installed | time=74ms
14:07:47.930 INFO: Load plugins index (done) | time=268ms
14:07:47.956 INFO: Load/download plugins (done) | time=293ms
14:07:47.986 WARN: Plugin Fortify [fortify] uses a child first classloader which is deprecated
14:07:48.363 DEBUG: Plugins:
14:07:48.364 DEBUG:   * Fortify 2.5 (fortify)

14:07:50.372 INFO: Skipping FPR file upload; SSC connection has not been configured

**Comment by rsenden** [comment]
This projects provides an integration between SonarQube and Fortify SSC, using the Fortify SSC REST API to retrieve issue details and metrics. As such, this integration does not read FPR files directly.
